#!/usr/bin/env bash
# oops — fix your last shell command with AI.
# This file is meant to be sourced from ~/.bashrc or ~/.zshrc.
# https://github.com/TheSolyboy/oops
# shellcheck shell=bash

OOPS_VERSION="0.1.0"
OOPS_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/oops"
OOPS_CONFIG_FILE="$OOPS_CONFIG_DIR/config"

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

_oops_load_config() {
  OOPS_PROVIDER=""
  OOPS_MODEL=""
  OOPS_API_KEY=""
  OOPS_BASE_URL=""
  if [ -f "$OOPS_CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    . "$OOPS_CONFIG_FILE"
  fi
}

_oops_save_config() {
  mkdir -p "$OOPS_CONFIG_DIR"
  ( umask 077; : > "$OOPS_CONFIG_FILE" )
  {
    printf '# oops configuration — generated by "oops config"\n'
    printf 'OOPS_PROVIDER="%s"\n' "$OOPS_PROVIDER"
    printf 'OOPS_MODEL="%s"\n' "$OOPS_MODEL"
    printf 'OOPS_API_KEY="%s"\n' "$OOPS_API_KEY"
    printf 'OOPS_BASE_URL="%s"\n' "$OOPS_BASE_URL"
  } > "$OOPS_CONFIG_FILE"
  chmod 600 "$OOPS_CONFIG_FILE" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Interactive prompts (always read from the terminal so this works under
# `curl ... | bash` where stdin is the piped script).
# ---------------------------------------------------------------------------

_oops_ask() {
  local prompt="$1" def="$2" ans=""
  if [ -n "$def" ]; then
    printf '%s [%s]: ' "$prompt" "$def" > /dev/tty
  else
    printf '%s: ' "$prompt" > /dev/tty
  fi
  IFS= read -r ans < /dev/tty || ans=""
  [ -z "$ans" ] && ans="$def"
  printf '%s' "$ans"
}

_oops_ask_secret() {
  local prompt="$1" ans=""
  printf '%s: ' "$prompt" > /dev/tty
  IFS= read -rs ans < /dev/tty || ans=""
  printf '\n' > /dev/tty
  printf '%s' "$ans"
}

_oops_setup() {
  _oops_load_config
  {
    printf '\n  oops setup\n'
    printf '  ----------\n\n'
    printf 'Select an AI provider:\n'
    printf '  1) Anthropic (Claude)\n'
    printf '  2) OpenRouter\n'
    printf '  3) Ollama (local)\n'
    printf '  4) OpenCode (opencode serve)\n'
  } > /dev/tty

  local choice
  choice=$(_oops_ask "Provider [1-4]" "1")
  case "$choice" in
    1|anthropic)  OOPS_PROVIDER="anthropic" ;;
    2|openrouter) OOPS_PROVIDER="openrouter" ;;
    3|ollama)     OOPS_PROVIDER="ollama" ;;
    4|opencode)   OOPS_PROVIDER="opencode" ;;
    *)            OOPS_PROVIDER="anthropic" ;;
  esac

  case "$OOPS_PROVIDER" in
    anthropic)
      OOPS_BASE_URL=""
      OOPS_API_KEY=$(_oops_ask_secret "Anthropic API key")
      OOPS_MODEL=$(_oops_ask "Model" "${OOPS_MODEL:-claude-haiku-4-5-20251001}")
      ;;
    openrouter)
      OOPS_BASE_URL=""
      OOPS_API_KEY=$(_oops_ask_secret "OpenRouter API key")
      OOPS_MODEL=$(_oops_ask "Model" "${OOPS_MODEL:-anthropic/claude-3.5-haiku}")
      ;;
    ollama)
      OOPS_API_KEY=""
      OOPS_BASE_URL=$(_oops_ask "Ollama base URL" "${OOPS_BASE_URL:-http://localhost:11434}")
      OOPS_MODEL=$(_oops_ask "Model" "${OOPS_MODEL:-llama3.2}")
      ;;
    opencode)
      printf 'opencode talks to a running "opencode serve" instance.\n' > /dev/tty
      printf 'The model must be "providerID/modelID" (e.g. anthropic/claude-haiku-4-5).\n' > /dev/tty
      OOPS_BASE_URL=$(_oops_ask "opencode server URL" "${OOPS_BASE_URL:-http://localhost:4096}")
      OOPS_API_KEY=$(_oops_ask_secret "API key (leave blank if none)")
      OOPS_MODEL=$(_oops_ask "Model (provider/model)" "${OOPS_MODEL:-anthropic/claude-haiku-4-5-20251001}")
      ;;
  esac

  _oops_save_config
  printf '\nSaved configuration to %s\n' "$OOPS_CONFIG_FILE" > /dev/tty
}

_oops_set() {
  local field="$1" value="$2"
  if [ -z "$value" ]; then
    printf 'usage: oops %s <value>\n' "$field" >&2
    return 1
  fi
  _oops_load_config
  case "$field" in
    model)
      OOPS_MODEL="$value"
      ;;
    provider)
      case "$value" in
        anthropic|openrouter|ollama|opencode) OOPS_PROVIDER="$value" ;;
        *)
          printf 'oops: unknown provider "%s" (anthropic|openrouter|ollama|opencode)\n' "$value" >&2
          return 1
          ;;
      esac
      ;;
  esac
  _oops_save_config
  printf 'oops: %s set to %s\n' "$field" "$value"
}

# ---------------------------------------------------------------------------
# JSON helpers (jq when available, pure-bash fallback otherwise)
# ---------------------------------------------------------------------------

_oops_json_escape() {
  local s
  s=$(cat)
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\t'/\\t}
  s=${s//$'\r'/\\r}
  s=${s//$'\n'/\\n}
  printf '%s' "$s"
}

_oops_json_unescape() {
  local s
  s=$(cat)
  s=${s//\\n/$'\n'}
  s=${s//\\t/$'\t'}
  s=${s//\\r/$'\r'}
  s=${s//\\\"/\"}
  s=${s//\\\\/\\}
  printf '%s' "$s"
}

# Reads a raw string on stdin, prints a quoted JSON string.
_oops_json_string() {
  if command -v jq >/dev/null 2>&1; then
    jq -Rs .
  else
    printf '"%s"' "$(_oops_json_escape)"
  fi
}

# Reads JSON on stdin, extracts a field. $1 is a jq filter.
_oops_json_get() {
  local filter="$1" input
  input=$(cat)
  [ -z "$input" ] && return 0
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$input" | jq -r "$filter // empty" 2>/dev/null
  else
    printf '%s' "$input" \
      | tr '\n' ' ' \
      | sed -n 's/.*"\(text\|content\)"[[:space:]]*:[[:space:]]*"\(\(\\.\|[^"\\]\)*\)".*/\2/p' \
      | head -n1 \
      | _oops_json_unescape
  fi
}

# ---------------------------------------------------------------------------
# Talking to the AI provider
# ---------------------------------------------------------------------------

_oops_request() {
  local cmd="$1" err="$2"
  local sys user sys_json user_json model_json
  sys='You are oops, a command-line assistant. The user just ran a shell command that failed. Given the failed command and its error output, reply with ONLY the corrected shell command to run instead. Output a single line: no explanation, no markdown, no code fences, no backticks, no surrounding quotes. If no fix is possible, output the original command unchanged.'
  user=$(printf 'Failed command:\n%s\n\nError output:\n%s' "$cmd" "$err")
  sys_json=$(printf '%s' "$sys" | _oops_json_string)
  user_json=$(printf '%s' "$user" | _oops_json_string)
  model_json=$(printf '%s' "$OOPS_MODEL" | _oops_json_string)

  # opencode speaks its own session-based API, not OpenAI chat completions.
  if [ "$OOPS_PROVIDER" = "opencode" ]; then
    _oops_request_opencode "$sys" "$user"
    return
  fi

  local url body filter
  local -a headers
  headers=(-H "content-type: application/json")

  case "$OOPS_PROVIDER" in
    anthropic)
      url="https://api.anthropic.com/v1/messages"
      headers+=(-H "x-api-key: $OOPS_API_KEY" -H "anthropic-version: 2023-06-01")
      body=$(printf '{"model":%s,"max_tokens":256,"system":%s,"messages":[{"role":"user","content":%s}]}' \
        "$model_json" "$sys_json" "$user_json")
      filter='.content[0].text'
      ;;
    openrouter)
      url="https://openrouter.ai/api/v1/chat/completions"
      headers+=(-H "Authorization: Bearer $OOPS_API_KEY")
      body=$(printf '{"model":%s,"messages":[{"role":"system","content":%s},{"role":"user","content":%s}]}' \
        "$model_json" "$sys_json" "$user_json")
      filter='.choices[0].message.content'
      ;;
    ollama)
      url="${OOPS_BASE_URL:-http://localhost:11434}/api/chat"
      body=$(printf '{"model":%s,"stream":false,"messages":[{"role":"system","content":%s},{"role":"user","content":%s}]}' \
        "$model_json" "$sys_json" "$user_json")
      filter='.message.content'
      ;;
    *)
      printf 'oops: unknown provider "%s". Run: oops config\n' "$OOPS_PROVIDER" >&2
      return 1
      ;;
  esac

  local raw out
  raw=$(curl -sS --max-time 30 "$url" "${headers[@]}" -d "$body" 2>&1)
  out=$(printf '%s' "$raw" | _oops_json_get "$filter")
  if [ -z "$out" ]; then
    printf 'oops: the provider returned no command. Raw response:\n%s\n' "$raw" >&2
    return 1
  fi
  printf '%s' "$out"
}

# opencode serve is an agentic coding server, not a chat-completions endpoint.
# Flow: create a session, post the prompt to it, read the assistant's text parts.
_oops_request_opencode() {
  local sys="$1" user="$2"
  local base prov mid sid
  local -a headers
  headers=(-H "content-type: application/json")
  [ -n "$OOPS_API_KEY" ] && headers+=(-H "Authorization: Bearer $OOPS_API_KEY")
  base="${OOPS_BASE_URL:-http://localhost:4096}"
  base="${base%/}"

  if ! command -v jq >/dev/null 2>&1; then
    printf 'oops: the opencode provider needs jq to parse responses. Install jq and retry.\n' >&2
    return 1
  fi

  prov="${OOPS_MODEL%%/*}"
  mid="${OOPS_MODEL#*/}"
  if [ -z "$mid" ] || [ "$prov" = "$OOPS_MODEL" ]; then
    printf 'oops: opencode needs OOPS_MODEL as "providerID/modelID" (e.g. anthropic/claude-haiku-4-5).\n' >&2
    printf '      Got "%s". Set it with: oops model <provider/model>\n' "$OOPS_MODEL" >&2
    return 1
  fi

  local create
  create=$(curl -sS --max-time 30 "$base/session" "${headers[@]}" -d '{"title":"oops"}' 2>&1)
  sid=$(printf '%s' "$create" | jq -r '.id // empty' 2>/dev/null)
  if [ -z "$sid" ]; then
    printf 'oops: could not create an opencode session at %s/session.\nResponse: %s\n' "$base" "$create" >&2
    return 1
  fi

  local text text_json prov_json mid_json body raw out
  text=$(printf '%s\n\n%s' "$sys" "$user")
  text_json=$(printf '%s' "$text" | _oops_json_string)
  prov_json=$(printf '%s' "$prov" | _oops_json_string)
  mid_json=$(printf '%s' "$mid" | _oops_json_string)
  body=$(printf '{"model":{"providerID":%s,"modelID":%s},"parts":[{"type":"text","text":%s}]}' \
    "$prov_json" "$mid_json" "$text_json")

  raw=$(curl -sS --max-time 120 "$base/session/$sid/message" "${headers[@]}" -d "$body" 2>&1)
  out=$(printf '%s' "$raw" | jq -r '[.parts[]? | select(.type=="text") | .text] | join("")' 2>/dev/null)
  if [ -z "$out" ]; then
    printf 'oops: opencode returned no text. Raw response:\n%s\n' "$raw" >&2
    return 1
  fi
  printf '%s' "$out"
}

# ---------------------------------------------------------------------------
# Output handling
# ---------------------------------------------------------------------------

_oops_clean() {
  local s="$1"
  s="${s//$'\r'/}"
  s=$(printf '%s\n' "$s" \
    | sed -e 's/^```[a-zA-Z]*//' -e 's/```$//' \
    | grep -m1 -v '^[[:space:]]*$')
  # trim surrounding whitespace
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  # unwrap if the whole command is wrapped in backticks
  case "$s" in
    \`*\`) s="${s#\`}"; s="${s%\`}" ;;
  esac
  printf '%s' "$s"
}

_oops_copy() {
  local text="$1"
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$text" | pbcopy && return 0
  fi
  if command -v wl-copy >/dev/null 2>&1; then
    printf '%s' "$text" | wl-copy && return 0
  fi
  if command -v xclip >/dev/null 2>&1; then
    printf '%s' "$text" | xclip -selection clipboard && return 0
  fi
  if command -v xsel >/dev/null 2>&1; then
    printf '%s' "$text" | xsel --clipboard --input && return 0
  fi
  return 1
}

# ---------------------------------------------------------------------------
# Finding the last command
# ---------------------------------------------------------------------------

_oops_last_command() {
  local line cmd=""
  while IFS= read -r line; do
    line="${line#"${line%%[![:space:]]*}"}"
    [ -z "$line" ] && continue
    case "$line" in
      oops|oops\ *|fuck|fuck\ *) continue ;;
    esac
    cmd="$line"
  done < <(fc -ln -10 2>/dev/null)
  printf '%s' "$cmd"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

_oops_run() {
  _oops_load_config
  if [ -z "$OOPS_PROVIDER" ]; then
    printf 'oops: not configured yet. Run: oops config\n' >&2
    return 1
  fi
  if ! command -v curl >/dev/null 2>&1; then
    printf 'oops: curl is required but not installed.\n' >&2
    return 1
  fi

  local cmd
  cmd=$(_oops_last_command)
  if [ -z "$cmd" ]; then
    printf 'oops: could not find a previous command in history.\n' >&2
    return 1
  fi

  printf 'oops: re-running "%s" to capture the error...\n' "$cmd" >&2
  local err
  err=$(eval "$cmd" 2>&1)
  err=$(printf '%s' "$err" | tail -c 4000)

  printf 'oops: asking %s (%s)...\n' "$OOPS_PROVIDER" "$OOPS_MODEL" >&2
  local fix
  if ! fix=$(_oops_request "$cmd" "$err"); then
    return 1
  fi
  fix=$(_oops_clean "$fix")
  if [ -z "$fix" ]; then
    printf 'oops: no suggestion returned.\n' >&2
    return 1
  fi

  printf '%s\n' "$fix"
  if _oops_copy "$fix"; then
    printf 'oops: copied to clipboard — paste with Ctrl+V (or Cmd+V) and press Enter.\n' >&2
  else
    printf 'oops: install xclip, xsel, or wl-clipboard to enable auto-copy.\n' >&2
  fi
}

_oops_help() {
  cat >&2 <<'EOF'
oops — fix your last shell command with AI

usage:
  oops                  fix the last command that failed
  oops config           re-run the interactive setup
  oops model <name>     switch the model (opencode wants "provider/model")
  oops provider <name>  switch provider (anthropic|openrouter|ollama|opencode)
  oops help             show this help
  oops version          show the version
EOF
}

oops() {
  case "${1:-}" in
    config)         _oops_setup ;;
    model)          _oops_set model "${2:-}" ;;
    provider)       _oops_set provider "${2:-}" ;;
    -h|--help|help) _oops_help ;;
    -v|--version|version) printf 'oops %s\n' "$OOPS_VERSION" ;;
    *)              _oops_run ;;
  esac
}
